### ISSUE TITLE
Not available in HACS

### ISSUE THREAD

**Issue by danielclindsay** [lovelace-rounded/ui#16]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am trying to install the current cards, but they are not avaiable in HACS as mentioned in the UI docs

### Describe the behavior you expected

To see the cards

### Steps to reproduce the issue

1. Go to HACS
2. Frontend
3. Search Rounded
...

### What version of Home Assistant Core has the issue?

latest

**Comment by acesyde** [comment]
Hi, 

That's because it's not available yet. 

Cards are not developed but it's coming in couple of weeks

**Comment by danielclindsay** [comment]
Ah okay, maybe update the UI docs just to let us know. Appreciate the work you are doing here :D

**Comment by dnestico** [comment]
Is it available in HACs yet? Docs ain't too clear...

**Comment by Fletcher-Alderton** [comment]
yea i cant find it
